# Generated by Django 4.1.7 on 2023-07-19 07:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_tata_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
